"use client";

import { useEffect, useRef, useState } from "react";

export default function CallClient(){
 const [type,setType]=useState<"voice"|"video">("voice"),[name,setName]=useState("My Gee"),[active,setActive]=useState(false),[status,setStatus]=useState("Ready"),[seconds,setSeconds]=useState(0),[muted,setMuted]=useState(false),[camera,setCamera]=useState(false),[error,setError]=useState("");
 const pcRef=useRef<RTCPeerConnection|null>(null),dcRef=useRef<RTCDataChannel|null>(null),streamRef=useRef<MediaStream|null>(null),audioRef=useRef<HTMLAudioElement|null>(null),videoRef=useRef<HTMLVideoElement|null>(null),timerRef=useRef<number|null>(null);
 const gender=name.toLowerCase().startsWith("emma")?"female":"male";
 useEffect(()=>{const p=new URLSearchParams(location.search);const t=p.get("type")==="video"?"video":"voice";setType(t);setName(p.get("name")||"My Gee");setCamera(t==="video");return()=>endCall(false)},[]);
 useEffect(()=>{if(!active)return;const id=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>window.clearInterval(id)},[active]);
 async function startCall(){if(active)return;setError("");setStatus("Connecting…");try{
   const pc=new RTCPeerConnection();pcRef.current=pc;
   const remote=document.createElement("audio");remote.autoplay=true;audioRef.current=remote;pc.ontrack=e=>{remote.srcObject=e.streams[0];remote.play().catch(()=>undefined)};
   const local=await navigator.mediaDevices.getUserMedia({audio:true,video:type==="video"});streamRef.current=local;local.getAudioTracks().forEach(t=>pc.addTrack(t,local));if(type==="video"){local.getVideoTracks().forEach(t=>pc.addTrack(t,local));if(videoRef.current){videoRef.current.srcObject=local;await videoRef.current.play().catch(()=>undefined)}}
   const dc=pc.createDataChannel("oai-events");dcRef.current=dc;dc.onopen=()=>{setStatus("Connected");dc.send(JSON.stringify({type:"response.create",response:{instructions:`Start naturally as ${name}. Keep it brief and conversational.`}}))};dc.onmessage=e=>{try{const ev=JSON.parse(e.data);if(ev.type==="input_audio_buffer.speech_started")setStatus("Listening…");else if(ev.type==="response.created")setStatus("Speaking…");else if(ev.type==="response.done")setStatus("Connected")}catch{}};
   const offer=await pc.createOffer();await pc.setLocalDescription(offer);const r=await fetch("/api/realtime/session",{method:"POST",headers:{"Content-Type":"application/sdp"},body:offer.sdp});if(!r.ok)throw new Error("Realtime call could not be started.");const answer=await r.text();await pc.setRemoteDescription({type:"answer",sdp:answer});setActive(true);setSeconds(0);setMuted(false);
 }catch(e){endCall(false);setStatus("Call failed");setError(e instanceof Error?e.message:"Could not start the call. Please try again.")}}
 function toggleMute(){const n=!muted;setMuted(n);streamRef.current?.getAudioTracks().forEach(t=>t.enabled=!n);setStatus(n?"Microphone muted":"Connected")}
 function toggleCamera(){const n=!camera;setCamera(n);streamRef.current?.getVideoTracks().forEach(t=>t.enabled=n)}
 function endCall(render=true){if(timerRef.current)clearInterval(timerRef.current);dcRef.current?.send(JSON.stringify({type:"session.close"}));dcRef.current?.close();pcRef.current?.close();streamRef.current?.getTracks().forEach(t=>t.stop());if(audioRef.current){audioRef.current.pause();audioRef.current.srcObject=null}pcRef.current=null;dcRef.current=null;streamRef.current=null;setActive(false);setMuted(false);if(render)setStatus("Call ended")}
 const mm=String(Math.floor(seconds/60)).padStart(2,"0"),ss=String(seconds%60).padStart(2,"0");
 return <main className="min-h-screen bg-black text-white p-6"><div className="mx-auto max-w-md"><div className="flex items-center justify-between mb-6"><button onClick={()=>history.back()} className="rounded-xl border border-white/10 px-3 py-2">← Back</button><div className="text-center"><div className="font-semibold">{name}</div><div className="text-xs text-white/50">{active?`${mm}:${ss} • ${status}`:status}</div></div><div className="w-16"/></div><div className="rounded-3xl bg-white/5 border border-white/10 p-6 min-h-[430px] flex flex-col justify-between">{type==="video"&&<video ref={videoRef} muted playsInline className="w-full rounded-2xl bg-black aspect-video object-cover"/>}<div className="text-center py-8"><div className="text-5xl mb-4">{active?"●":"☎"}</div><div className="text-lg">{active?"Live conversation":"Ready when you are."}</div><div className="text-sm text-white/50 mt-2">{active?"Speak naturally. You can interrupt when you want.":"Tap Start to connect."}</div></div><div className="flex gap-3 pt-6"><button onClick={startCall} disabled={active} className="flex-1 rounded-2xl bg-white text-black py-4 font-semibold">Start call</button><button onClick={toggleMute} disabled={!active} className="rounded-2xl border border-white/10 px-4 py-4">{muted?"Unmute":"Mute"}</button>{type==="video"&&<button onClick={toggleCamera} disabled={!active} className="rounded-2xl border border-white/10 px-4 py-4">{camera?"Cam off":"Cam on"}</button>}<button onClick={()=>endCall()} disabled={!active} className="rounded-2xl border border-red-400/30 px-4 py-4">End</button></div>{error&&<div className="mt-4 text-sm text-red-300">{error}</div>}</div></div></main>
}