"use client";

import { useEffect, useRef, useState } from "react";

type ChatMessage = { role: "user" | "assistant"; content: string };
type RecognitionLike = { lang: string; continuous?: boolean; interimResults?: boolean; start: () => void; stop: () => void; onresult: ((event: any) => void) | null; onend: (() => void) | null; onerror: ((event: any) => void) | null };
declare global { interface Window { SpeechRecognition?: new () => RecognitionLike; webkitSpeechRecognition?: new () => RecognitionLike; } }

export default function CallClient() {
  const [type,setType]=useState<"voice"|"video">("voice"),[name,setName]=useState("Gee friend"),[status,setStatus]=useState("Ready"),[seconds,setSeconds]=useState(0),[muted,setMuted]=useState(false),[camera,setCamera]=useState(false),[active,setActive]=useState(false),[listening,setListening]=useState(false),[speaking,setSpeaking]=useState(false),[error,setError]=useState(""),[reply,setReply]=useState(""),[transcript,setTranscript]=useState("");
  const streamRef=useRef<MediaStream|null>(null),videoRef=useRef<HTMLVideoElement|null>(null),recognitionRef=useRef<RecognitionLike|null>(null),audioRef=useRef<HTMLAudioElement|null>(null),activeRef=useRef(false),busyRef=useRef(false),restartRef=useRef(true),timerRef=useRef<ReturnType<typeof setTimeout>|null>(null),historyRef=useRef<ChatMessage[]>([]);
  const isElijah=name.toLowerCase().startsWith("elijah"); const isEmma=name.toLowerCase().startsWith("emma");
  useEffect(()=>{const p=new URLSearchParams(window.location.search);const t=p.get("type")==="video"?"video":"voice";setType(t);setName(p.get("name")||"Gee friend");setCamera(t==="video");return()=>stopCall(false)},[]);
  useEffect(()=>{if(!active)return;const id=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>window.clearInterval(id)},[active]);
  async function ensureMedia(){if(streamRef.current)return true;if(!navigator.mediaDevices?.getUserMedia){setError("Your browser does not support microphone/camera access. Use Chrome on Android.");return false}try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:type==="video"});streamRef.current=s;if(videoRef.current&&type==="video"){videoRef.current.srcObject=s;await videoRef.current.play().catch(()=>undefined)}return true}catch{setError(type==="video"?"Please allow camera and microphone access.":"Please allow microphone access.");return false}}
  async function speak(text:string){setSpeaking(true);try{const gender=isElijah?"male":isEmma?"female":"male";const r=await fetch("/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,companionName:name,gender})});if(!r.ok)throw new Error("AI voice could not be generated. Please try the call again.");const blob=await r.blob(),url=URL.createObjectURL(blob),audio=audioRef.current||new Audio();audioRef.current=audio;audio.src=url;audio.preload="auto";audio.volume=1;await audio.play();await new Promise<void>((resolve,reject)=>{audio.onended=()=>resolve();audio.onerror=()=>reject(new Error("Audio playback failed."))});URL.revokeObjectURL(url)}finally{setSpeaking(false)}}
  async function answer(text:string){if(busyRef.current||!activeRef.current)return;const clean=text.trim();if(!clean)return;busyRef.current=true;restartRef.current=false;setStatus("Thinking…");setError("");try{const messages=[...historyRef.current.slice(-10),{role:"user" as const,content:clean}];const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companionName:name,languageStyle:"english",messages})});if(!r.ok)throw new Error("GEE could not connect right now.");const d=await r.json();const fallback=isElijah?"I get you. That sounds like a lot to deal with. What happened?":isEmma?"I get you. That sounds really difficult. What happened?":`I get you. That sounds difficult.`;const next=String(d.reply||fallback).trim();historyRef.current=[...messages,{role:"assistant",content:next}].slice(-12);setReply(next);await speak(next)}catch(e){setError(e instanceof Error?e.message:"I couldn't answer right now.")}finally{busyRef.current=false;if(activeRef.current){setStatus("Connected");restartRef.current=true;timerRef.current=setTimeout(beginListening,300)}}}
  function beginListening(){if(!activeRef.current||busyRef.current||muted)return;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){setError("Voice input is not supported. Use Chrome on Android.");return}try{recognitionRef.current?.stop();const rec=new Recognition();recognitionRef.current=rec;rec.lang="en-GB";rec.continuous=false;rec.interimResults=false;let got=false;restartRef.current=true;setListening(true);setStatus("Listening…");rec.onresult=async e=>{got=true;setListening(false);const text=String(e.results?.[0]?.[0]?.transcript||"").trim();if(text){setTranscript(text);await answer(text)}};rec.onerror=e=>{setListening(false);if(e?.error==="not-allowed"||e?.error==="service-not-allowed"){restartRef.current=false;setError("Microphone permission is blocked. Allow microphone access in Chrome.")}else if(e?.error!=="aborted")setError("I couldn't hear you. Tap to speak again.")};rec.onend=()=>{setListening(false);if(!got&&restartRef.current&&activeRef.current&&!busyRef.current&&!muted)timerRef.current=setTimeout(beginListening,400)};rec.start()}catch{setListening(false);setError("Tap to speak again.")}}
  async function startCall(){if(active)return beginListening();setError("");setStatus(type==="video"?"Starting video call…":"Connecting voice…");if(!(await ensureMedia()))return;activeRef.current=true;restartRef.current=true;historyRef.current=[];setActive(true);setSeconds(0);setMuted(false);if(type==="video")setCamera(true);const greeting=isElijah?"Hey Elijah here. Good to hear from you. What's going on?":isEmma?"Hey, it's Emma. Good to hear from you. What's going on?":`Hey, it's ${name}. What's going on?`;setReply(greeting);try{await speak(greeting)}catch(e){setError(e instanceof Error?e.message:"Voice playback failed.")}setStatus("Connected");beginListening()}
  function toggleMute(){const n=!muted;setMuted(n);streamRef.current?.getAudioTracks().forEach(t=>(t.enabled=!n));if(n){recognitionRef.current?.stop();setListening(false);setStatus("Microphone muted")}else{setStatus("Connected");beginListening()}}
  function toggleCamera(){const n=!camera;setCamera(n);streamRef.current?.getVideoTracks().forEach(t=>(t.enabled=n))}
  function stopCall(render=true){activeRef.current=false;restartRef.current=false;recognitionRef.current?.stop();if(timerRef.current)clearTimeout(timerRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(audioRef.current){audioRef.current.pause();audioRef.current.src=""}setActive(false);setListening(false);setSpeaking(false);if(render)setStatus("Call ended")}
  const mm=String(Math.floor(seconds/60)).padStart(2,"0"),ss=String(seconds%60).padStart(2,"0");
  return <main className="min-h-screen bg-black text-white p-6"><div className="mx-auto max-w-md"><div className="flex items-center justify-between mb-6"><button onClick={()=>window.history.back()} className="rounded-xl border border-white/10 px-3 py-2">← Back</button><div className="text-center"><div className="font-semibold">{name}</div><div className="text-xs text-white/50">{active?`${mm}:${ss} • ${speaking?"Speaking":listening?"Listening":"Connected"}`:status}</div></div><div className="w-16"/></div><div className="rounded-3xl bg-white/5 border border-white/10 p-6 min-h-[430px] flex flex-col justify-between">{type==="video"&&<video ref={videoRef} muted playsInline className="w-full rounded-2xl bg-black aspect-video object-cover"/>}<div><div className="text-xs text-white/50 mb-2">{transcript?`You: ${transcript}`:"Live conversation"}</div><div className="text-lg leading-8">{reply||"Ready when you are."}</div></div><div className="flex gap-3 pt-6"><button onClick={startCall} className="flex-1 rounded-2xl bg-white text-black py-4 font-semibold">{active?"Speak":"Start voice"}</button><button onClick={toggleMute} disabled={!active} className="rounded-2xl border border-white/10 px-4 py-4">{muted?"Unmute":"Mute"}</button>{type==="video"&&<button onClick={toggleCamera} disabled={!active} className="rounded-2xl border border-white/10 px-4 py-4">{camera?"Cam off":"Cam on"}</button>}<button onClick={()=>stopCall()} disabled={!active} className="rounded-2xl border border-red-400/30 px-4 py-4">End</button></div>{error&&<div className="mt-4 text-sm text-red-300">{error}</div>}</div></div></main>
}